# Generated by Django 5.1.4 on 2024-12-28 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_alter_comment_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post_comment_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='comment.post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post_comment_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='comment.post'),
        ),
    ]
